# Generated by: wf-gen from tyk-ci
# Generated at: Sat 18 Jul 12:39:53 IST 2020

data "terraform_remote_state" "integration" {
  backend = "remote"

  config = {
    organization = "Tyk"
    workspaces = {
      name = "base-euc1"
    }
  }
}

output "gromit" {
  value       = data.terraform_remote_state.integration.outputs.gromit
  description = "ECR creds for gromit repo"
}

output "region" {
  value       = data.terraform_remote_state.integration.outputs.region
  description = "Region in which the developer env is running"
}
