define(xDATE, esyscmd(date))dnl
dnl The comment below is quoted so that it is not treated as a comment
`#' Generated on: xDATE
# Generated by: wf-gen from tyk-ci

FROM debian:buster-slim

ADD xREPO.tar.gz /opt/xREPO

VOLUME ["/conf"]
WORKDIR /opt/xREPO

ENTRYPOINT ["/opt/xREPO/xREPO" ]
CMD [ "--conf=/conf/xREPO/xREPO.conf" ]
# Local Variables:
# mode: dockerfile
# End:
