version: "3.9"
services:
  bundle-server:
    profiles: ["all", "master-datacenter"]
    container_name: bundle-server
    build:
      context: ./bundle-server
    ports:
      - "8000:8000"

  federation-server:
    profiles: ["all", "master-datacenter"]
    container_name: federation
    image: agatawitkowska/federation-example
    ports:
      - "4000:4000"
      - "4001:4001"
      - "4002:4002"
      - "4003:4003"

  openldap:
    profiles: ["all", "master-datacenter"]
    container_name: openldap
    image: osixia/openldap:1.5.0
    ports:
      - "389:389"
      - "636:636"
    environment:
      - LDAP_READONLY_USER=true
      - LDAP_READONLY_USER_USERNAME=read-only-admin
      - LDAP_READONLY_USER_PASSWORD=password

  graphql-faker:
    profiles: ["all", "master-datacenter"]
    container_name: graphql-faker
    image: apisguru/graphql-faker:latest
    volumes:
      - ./faker-schema.graphql:/workdir/faker-schema.graphql
    command: "faker-schema.graphql"
    ports:
      - "9002:9002"

  upstream:
    profiles: ["all", "master-datacenter"]
    container_name: httpbin.org
    image: kennethreitz/httpbin
    restart: always

  restcountries:
    profiles: ["all", "master-datacenter"]
    container_name: restcountries
    image: bigpapoo/restcountries:1.0

  trevorblades:
    profiles: ["all", "master-datacenter"]
    container_name: trevorblades
    image: mangomm/trevorblades-countries

  webhook:
    profiles: ["all", "master-datacenter"]
    container_name: webhook-server
    build:
      context: ./webhook-server
    ports:
      - "9003:9003"

  kafka:
    image: apache/kafka:3.8.0  # Replace with the desired Kafka version
    container_name: kafka
    ports:
      - "9094:9094"
    environment:
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9093
      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093,EXTERNAL://:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,EXTERNAL://localhost:9094
      KAFKA_METADATA_LOG_DIR: /var/lib/kafka/data
      KAFKA_LOG_DIRS: /var/lib/kafka/data
    volumes:
      - ./temp/kafka/data:/var/lib/kafka/data