version: "3"
services:
  redis:
    profiles: ["all", "master-datacenter"]
    container_name: redis
    image: bitnami/redis:7.0.15
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 5s
      retries: 10
      start_period: 2s
      timeout: 10s

  redis-datacenter-1:
    profiles: ["all", "slave-datacenter"]
    container_name: redis-datacenter-1
    image: bitnami/redis:7.0.15
    environment:
      - ALLOW_EMPTY_PASSWORD=yes    
    ports:
      - "6381:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 5s
      retries: 10
      start_period: 2s
      timeout: 10s

  redis-datacenter-2:
    profiles: ["all", "slave-datacenter"]
    container_name: redis-datacenter-2
    image: bitnami/redis:7.0.15
    environment:   
      - ALLOW_EMPTY_PASSWORD=yes    
    ports:
      - "6382:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 5s
      retries: 10
      start_period: 2s
      timeout: 10s

  wait_redis:
    profiles: ["all", "master-datacenter"]
    image: hello-world:linux
    depends_on:
        redis:
            condition: service_healthy      