---
version: "3"

tasks:
  login:
    desc: Logins into AWS ECR registry to allow pull required images from it
    cmds:
      - aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 754489498669.dkr.ecr.eu-central-1.amazonaws.com

  bootstrap:
    desc: Bootstraps dashboard with an organization and user
    cmds:
      - sleep 8
      - ./dash-bootstrap.sh http://localhost:3000
      - sleep 8

  local:
    desc: Deploys infrastructure locally using docker compose manifest
    env:
      FLAVOUR: '{{ or .FLAVOUR "pro" }}'
      DB: '{{ or .DB "mongo44" }}'
      CACHE: '{{ or .CACHE "redis6" }}'
      VARIATION: '{{or .VARIATION "murmur64" }}'
      confs_dir: './{{ .FLAVOUR }}'
      env_file: local-{{.DB}}.env
    cmds:
      - |
        git checkout -f confs/${VARIATION}.env
        cat "confs/${VARIATION}.env" "${env_file}" | sort -u > tmp.env
        mv tmp.env ${env_file}
        docker compose -p auto -f ${FLAVOUR}.yml -f deps_${FLAVOUR}.yml -f ${DB}.yml -f ${CACHE}.yml --env-file master.env --profile master-datacenter up --quiet-pull -d
        if [[ "${FLAVOUR}" == "pro-ha" ]];then
          task bootstrap
          docker compose -p auto -f pro-ha.yml -f deps_pro-ha.yml -f ${DB}.yml -f ${CACHE}.yml --env-file master.env --profile slave-datacenter up --quiet-pull -d
        fi


  clean:
    desc: Tears down all local infrastructure including networking
    env:
      FLAVOUR: '{{ or .FLAVOUR "pro" }}'
      DB: '{{ or .DB "mongo44" }}'
      CACHE: '{{ or .CACHE "redis6" }}'
      VARIATION: '{{or .VARIATION "murmur64" }}'
      confs_dir: './{{ .FLAVOUR }}'
      env_file: local-{{.DB}}.env
    cmds:
      - docker compose -p auto -f ${FLAVOUR}.yml -f deps_${FLAVOUR}.yml -f ${DB}.yml -f ${CACHE}.yml --env-file master.env --env-file master.env --profile all down --remove-orphans
      - docker volume prune -f

  pytest:
    desc: |
      Deploys pytest container that runs against local infrastructure using docker compose manifest
      - For mdcb you may want to use the ARGS "--ci -m "mdcb""
      - For non mdcb deployments something like "-m "not local and not mdcb""
    cmds: 
      - |
        docker run --rm --network auto_default --env-file ./pytest.env \
        754489498669.dkr.ecr.eu-central-1.amazonaws.com/tyk-automated-tests:master \
        pytest -c pytest_ci.ini {{.CLI_ARGS}}

  healthcheck:
    desc: Usefull healthchecks to ensure services are up and running
    cmds:
      - echo "---Gateway Status---"
      - curl -s --fail -k https://"{{.HOST}}":8080/hello
    vars:
      HOST: localhost
