name: Infra Apply

on:
  push:
    branches:
      - master

defaults:
  run:
    working-directory: ./infra

jobs:
  apply:
    env:
      TF_CLI_ARGS: -no-color
      TF_WORKSPACE: prod
      CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
          
      - uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
        
      - name: Configure AWS credentials for use
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: eu-central-1
          
      - name: validate
        id: validate
        run: |
          terraform init
          terraform validate
        
      - name: apply
        id: apply
        run: |
          terraform apply -auto-approve -var-file ${TF_WORKSPACE}.tfvars
