AWSTemplateFormatVersion: '2010-09-09'
Description: ChatOps with Integration environments

Parameters:
  BotRole:
    Description: Privileges that the bot will have
    Default: arn:aws:iam::754489498669:role/gromit
    Type: String
  SlackChannelID:
    Default: C01FQK3PDUP
    Description: "Channel ID to use (default: #integration)"
    Type: String
    AllowedPattern: "[a-zA-Z][a-zA-Z0-9]+"

Resources:
  ChatTopic:
    Type: AWS::SNS::Topic
    Properties: 
      DisplayName: ChatOps
      Tags: 
        - Key: "managed"
          Value: "cfn"
        - Key: "purpose"
          Value: "cd"
        - Key: "ou"
          Value: "devops"
      TopicName: IntegrationEnvs

  SlackIntegration:
    Type: AWS::Chatbot::SlackChannelConfiguration
    Properties: 
      ConfigurationName: Gromit
      IamRoleArn: !Ref BotRole
      SlackChannelId: !Ref SlackChannelID
      SlackWorkspaceId: T0ATUMNSJ
      SnsTopicArns: 
        - !Ref ChatTopic
